source "https://rubygems.org"

gem "cocoapods", "~> 1.14"
gem "fastlane", "~> 2.220"

# Fastlane plugins
plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval(File.read(plugins_path)) if File.exist?(plugins_path)
