# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '15.1'
prepare_react_native_project!

# Fix boost.podspec URL to use working mirror
boost_podspec = File.join(__dir__, '..', 'node_modules', 'react-native', 'third-party-podspecs', 'boost.podspec')
if File.exist?(boost_podspec)
  content = File.read(boost_podspec)
  if content.include?('boostorg.jfrog.io')
    File.write(boost_podspec, content.gsub(
      'https://boostorg.jfrog.io/artifactory/main/release/1.83.0/source/boost_1_83_0.tar.bz2',
      'https://archives.boost.io/release/1.83.0/source/boost_1_83_0.tar.bz2'
    ))
    puts "✅ Fixed boost.podspec URL"
  end
end

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'read_en' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
  

  target 'read_enTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    # Fix for RCT-Folly warnings treated as errors on Xcode 16+ with iOS 18
    installer.pods_project.targets.each do |target|
      if target.name == 'RCT-Folly'
        target.build_configurations.each do |config|
          config.build_settings['GCC_TREAT_WARNINGS_AS_ERRORS'] = 'NO'
          config.build_settings['CLANG_WARN_DEPRECATED_THIS_CAPTURE'] = 'NO'
        end
      end

      # Suppress warnings for YandexMobileAds and allow duplicated symbols (YandexMobileAds 5.5.0 has duplicate object files)
      if target.name == 'read_en' || target.name == 'Pods-read_en'
        target.build_configurations.each do |config|
          config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = 'YES'
          config.build_settings['LD_ALLOW_DUPLICATED_SYMBOLS'] = 'YES'
        end
      end
    end
  end
end
